M48
; DRILL file {KiCad (7.0.0-0)} date Thursday, 16 March 2023 at 16:39:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-16T16:39:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X142.525Y-137.25
X145.875Y-137.25
T2
X105.596Y-99.5
X105.596Y-130.5
T0
M30
